<tr class="row0">
<th class="col0"> Дата <br>
выхода </th><th class="col1"> Сайт <br>
Название </th><th class="col2"> Последняя <br>
версия </th><th class="col3"> Автор </th><th class="col4"> Скачать </th><th class="col5"> Протокол </th><th class="col6"> Комментарий </th>
</tr>
<tr class="row1">
<td class="col0"> 2010/05/23 </td><td class="col1"> <a href="http://members.ziggo.nl/allard.siemelink/spark/" class="urlextern" title="http://members.ziggo.nl/allard.siemelink/spark/" rel="nofollow"> Spark</a> </td><td class="col2 centeralign">  0.4  </td><td class="col3"> Allard Siemelink (Аллард Симмелинк) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> win32+64, linux64; 40 ЭЛО сильнее прошлой версии, исправлены ошибки) </td>
</tr>
<tr class="row2">
<td class="col0"> 2010/05/23 </td><td class="col1"> <a href="http://sourceforge.net/projects/critterchess/" class="urlextern" title="http://sourceforge.net/projects/critterchess/" rel="nofollow"> Critter</a> </td><td class="col2 centeralign">  0.70  </td><td class="col3"> Richard Vida (Рихард Вида) </td><td class="col4 centeralign">  <a href="http://www.mediafire.com/?zjmnggirnzw" class="urlextern" title="http://www.mediafire.com/?zjmnggirnzw" rel="nofollow"> 0.70 exe</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на Object Pascal (Delphi) (для старой версии), для новой версии исходники закрыты; Win32/64; mp </td>
</tr>
<tr class="row3">
<td class="col0"> 2010/05/23 </td><td class="col1"> <a href="http://sourceforge.net/projects/umko/" class="urlextern" title="http://sourceforge.net/projects/umko/" rel="nofollow"> Umko</a> </td><td class="col2 centeralign">  0.9  </td><td class="col3"> Borko Boskovic (Борко Бошкович) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на C++; mp; Win32/64; дериват Fruit'а </td>
</tr>
<tr class="row4">
<td class="col0"> 2010/05/21 </td><td class="col1"> <a href="http://www.chessbin.com/page/Download-Chess-Bin-Chess-Game.aspx" class="urlextern" title="http://www.chessbin.com/page/Download-Chess-Bin-Chess-Game.aspx" rel="nofollow"> ChessBin</a> </td><td class="col2 centeralign">  0.0.7.3  </td><td class="col3"> Adam Berent (Адам Берент) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32; требует установленный .NET Framework 2.0 и выше; собственная <acronym title="Graphical User Interface">GUI</acronym> </td>
</tr>
<tr class="row5">
<td class="col0"> 2010/05/21 </td><td class="col1"> <strong><a href="http://www.hiarcs.com/" class="urlextern" title="http://www.hiarcs.com/" rel="nofollow"> Hiarcs</a></strong> </td><td class="col2 centeralign">  13.1  </td><td class="col3"> Mark Uniacke (Марк Юниаке) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> <strong>Коммерческий</strong>; FRC; Win32/64, Mac; Win32; mp </td>
</tr>
<tr class="row6">
<td class="col0"> 2010/05/21 </td><td class="col1"> <a href="http://www.wix.com/pedrox/caligula" class="urlextern" title="http://www.wix.com/pedrox/caligula" rel="nofollow"> Caligula</a> </td><td class="col2 centeralign">  0.7b  </td><td class="col3"> Pedro Castro (Педро Кастро) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32; основан на TSCP, использует битбазы Scorpio и дебютные книги Polyglot </td>
</tr>
<tr class="row7">
<td class="col0"> 2010/05/21 </td><td class="col1"> <a href="http://sites.google.com/site/danasah/" class="urlextern" title="http://sites.google.com/site/danasah/" rel="nofollow"> DanaSah</a> </td><td class="col2 centeralign">  4.45  </td><td class="col3"> Pedro Castro (Педро Кастро) </td><td class="col4 centeralign">  <a href="http://sites.google.com/site/danasah/danasah445.zip?attredirects=0" class="urlextern" title="http://sites.google.com/site/danasah/danasah445.zip?attredirects=0" rel="nofollow"> 4.45-ый build</a>  </td><td class="col5 centeralign">  WB, UCI  </td><td class="col6"> Исходники на C (комментарии на испанском); Linux; FRC; использует битбазы Scorpio и дебютную книгу ProDeo </td>
</tr>
<tr class="row8">
<td class="col0"> 2010/05/20 </td><td class="col1"> Komodo </td><td class="col2 centeralign">  1.2  </td><td class="col3"> Don Dailey &amp; Larry Kaufman (Дон Дейли и Ларри Кауфман) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a> <a href="http://www.file-upload.net/download-2519072/komodoBook.zip.html" class="urlextern" title="http://www.file-upload.net/download-2519072/komodoBook.zip.html" rel="nofollow"> Дебютная книга от Сальво Спитальери</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Win32/64, Linux32/64; только одноядерный </td>
</tr>
<tr class="row9">
<td class="col0"> 2010/05/18 </td><td class="col1"> <strong><a href="http://www.hiarcs.com/pc-chess-deep-junior.htm" class="urlextern" title="http://www.hiarcs.com/pc-chess-deep-junior.htm" rel="nofollow"> Junior (Deep Junior)</a></strong> </td><td class="col2 centeralign">  11.2  </td><td class="col3"> Amir Ban &amp; Shay Bushinsky (Амир Бан и Шай Бушинский) </td><td class="col4 centeralign">  <a href="http://www.worldchesslive.com/bj/index.html" class="urlextern" title="http://www.worldchesslive.com/bj/index.html" rel="nofollow"> Сайт с оболочкой Bobby Junior</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> <strong>Коммерческий</strong>; mp; Win32/64 </td>
</tr>
<tr class="row10">
<td class="col0"> 2010/05/18 </td><td class="col1"> <a href="http://eloxoph.com/ildtiadar/" class="urlextern" title="http://eloxoph.com/ildtiadar/" rel="nofollow"> Ildtiadar</a> </td><td class="col2 centeralign">  0.9c  </td><td class="col3"> Jonas Thiem (Йонас Тьем) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32, Linux32 </td>
</tr>
<tr class="row11">
<td class="col0"> 2010/05/18 </td><td class="col1"> <a href="http://www.pvv.ntnu.no/~jacobbl/jacob/Sjakk/Sjakk.htm" class="urlextern" title="http://www.pvv.ntnu.no/~jacobbl/jacob/Sjakk/Sjakk.htm" rel="nofollow"> Sjakk</a> </td><td class="col2 centeralign">  1.1.5  </td><td class="col3"> Jacob Børs Lind (Якоб Линд) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32; своя <acronym title="Graphical User Interface">GUI</acronym> </td>
</tr>
<tr class="row12">
<td class="col0"> 2010/05/18 </td><td class="col1"> <a href="http://sites.google.com/site/mychessengines/" class="urlextern" title="http://sites.google.com/site/mychessengines/" rel="nofollow"> Tornado</a> </td><td class="col2 centeralign">  3.51a  </td><td class="col3"> Engin Üstün (Энгин Устюн) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> FRC; multi-pv; mp, Win32/64; ограничение силы игры; своя дебютная книга </td>
</tr>
<tr class="row13">
<td class="col0"> 2010/05/17 </td><td class="col1"> <a href="http://digilander.libero.it/taioscacchi/programmi/saros-page.html" class="urlextern" title="http://digilander.libero.it/taioscacchi/programmi/saros-page.html" rel="nofollow"> Deep Saros</a> </td><td class="col2 centeralign">  0.9  </td><td class="col3"> Roberto Munter (Роберто Мунтер) </td><td class="col4 centeralign">  <a href="http://www.mediafire.com/download.php?uyzjzmzyjzm" class="urlextern" title="http://www.mediafire.com/download.php?uyzjzmzyjzm" rel="nofollow"> Denis Mendoza</a> <a href="http://www.mediafire.com/?ynhhyd0ihzn" class="urlextern" title="http://www.mediafire.com/?ynhhyd0ihzn" rel="nofollow"> libiomp5md.dll от него же</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> C++ исходники; mp; Win32, Linux32/64; Toga дериват </td>
</tr>
<tr class="row14">
<td class="col0"> 2010/05/17 </td><td class="col1"> <a href="http://sites.google.com/site/butterflychess/" class="urlextern" title="http://sites.google.com/site/butterflychess/" rel="nofollow"> Butterfly</a> </td><td class="col2 centeralign">  0.3.2  </td><td class="col3"> Giuseppe Cannella (Джузеппе Каннелла) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C++; Win32/64, Linux32/64 от JA; Win32/64 доступны и на домашней странице </td>
</tr>
<tr class="row15">
<td class="col0"> 2010/05/16 </td><td class="col1"> <a href="http://www.cruxis.com/chess/houdini.htm" class="urlextern" title="http://www.cruxis.com/chess/houdini.htm" rel="nofollow"> Houdini</a> </td><td class="col2 centeralign">  1.0, build 2010-05-16  </td><td class="col3"> Robert Houdart (Робер Гудар) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Win32/64, mp (2-cpu максимум), дериват «ипполитов» </td>
</tr>
<tr class="row16">
<td class="col0"> 2010/05/16 </td><td class="col1"> <a href="http://home.kpn.nl/rogerbroertjes/" class="urlextern" title="http://home.kpn.nl/rogerbroertjes/" rel="nofollow"> RBrChess</a> </td><td class="col2 centeralign">  2.21  </td><td class="col3"> Roger Broertjes (Роджер Брортьес) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32/64 </td>
</tr>
<tr class="row17">
<td class="col0"> 2010/05/15 </td><td class="col1"> <a href="http://www.onnochess.com/index.html" class="urlextern" title="http://www.onnochess.com/index.html" rel="nofollow"> (Deep) Onno</a> </td><td class="col2 centeralign">  1-2-70  </td><td class="col3"> Onno Garms (Онно Гармс) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> <strong>Коммерческий</strong>; Win32/64; mp </td>
</tr>
<tr class="row18">
<td class="col0"> 2010/05/15 </td><td class="col1"> AliBaba </td><td class="col2 centeralign">  1.28wb JA  </td><td class="col3"> Dennis Breuker &amp; Jim Ablett (Деннис Бройкер и Джим Аблетт) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a> <a href="http://cap.connx.com/Alibaba/" class="urlextern" title="http://cap.connx.com/Alibaba/" rel="nofollow"> Dann Corbit</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6 leftalign"> Исходники на C; исправленная JA версия; Win32, Linux32; Код AliBaba развивиается с 1995 года; Компиляция от DC устарела  </td>
</tr>
<tr class="row19">
<td class="col0"> 2010/05/14 </td><td class="col1"> <a href="http://code.google.com/p/chess-at-nite/" class="urlextern" title="http://code.google.com/p/chess-at-nite/" rel="nofollow"> Chess-at-nite</a> </td><td class="col2 centeralign">  10.1.31  </td><td class="col3"> Franziskus Domig, Panayiotis Lipiridis, Radoslav Petrik and Thai Gia Tuong </td><td class="col4 centeralign">  <a href="http://www.petrik.us/projects/ChessComputer.pdf" class="urlextern" title="http://www.petrik.us/projects/ChessComputer.pdf" rel="nofollow"> project description</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> C++ исходники; Win32, Linux32 &amp;amp; Mac </td>
</tr>
<tr class="row20">
<td class="col0"> 2010/05/14 </td><td class="col1"> <a href="http://sourceforge.net/projects/chesley/" class="urlextern" title="http://sourceforge.net/projects/chesley/" rel="nofollow"> Chesley the Chess Engine</a> </td><td class="col2 centeralign">  r323  </td><td class="col3"> Matthew Gingell (Мэтью Джинджелл) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> На домашней странице выложены только исходники в C++; использует библиотеку Boost; Win32/64 версии, Linux; последний билд от JA: r322 </td>
</tr>
<tr class="row21">
<td class="col0"> 2010/05/14 </td><td class="col1"> <a href="http://sites.google.com/site/pliskchess/" class="urlextern" title="http://sites.google.com/site/pliskchess/" rel="nofollow"> Plisk</a> </td><td class="col2 centeralign">  0.2.3h  </td><td class="col3"> Vlad Stamate (Влад Стамате) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB, UCI  </td><td class="col6"> Win32/64, AMD64, &amp; Linux32 </td>
</tr>
<tr class="row22">
<td class="col0"> 2010/05/10 </td><td class="col1"> <a href="http://fsharpchess.codeplex.com/" class="urlextern" title="http://fsharpchess.codeplex.com/" rel="nofollow"> FSharpChess</a> </td><td class="col2 centeralign">  0.197  </td><td class="col3"> Phil Brooks (Фил Брукс) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> портация SharpChess на язык F#; своя <acronym title="Graphical User Interface">GUI</acronym> </td>
</tr>
<tr class="row23">
<td class="col0"> 2010/05/09 </td><td class="col1"> Easy Peasy </td><td class="col2 centeralign">  ???  </td><td class="col3"> ??? </td><td class="col4 centeralign">  <a href="http://www.mayura.com/chess/" class="urlextern" title="http://www.mayura.com/chess/" rel="nofollow"> Mayura Chess Board</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Win32; составная часть Mayura Chess Board <acronym title="Graphical User Interface">GUI</acronym> </td>
</tr>
<tr class="row24">
<td class="col0"> 2010/05/02 </td><td class="col1"> <a href="http://b0n0.free.fr/bsc/bsc.html" class="urlextern" title="http://b0n0.free.fr/bsc/bsc.html" rel="nofollow"> BSC</a> </td><td class="col2 centeralign">  3.8  </td><td class="col3"> Nicolas Robert (Николя Робер) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32, Linux32/64 и Solaris x64 </td>
</tr>
<tr class="row25">
<td class="col0"> 2010/05/02 </td><td class="col1"> <a href="http://andchess2006.narod.ru" class="urlextern" title="http://andchess2006.narod.ru" rel="nofollow"> Ifrit</a> </td><td class="col2 centeralign">  j3.1  </td><td class="col3"> Андрей Скрытный </td><td class="col4 centeralign">  <a href="http://andchess2006.narod.ru/bin_ifrit_j/Ifrit_j3_1.zip" class="urlextern" title="http://andchess2006.narod.ru/bin_ifrit_j/Ifrit_j3_1.zip" rel="nofollow"> Ifrit</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на C++ (комментарии на <em>русском языке</em>!); Win32 </td>
</tr>
<tr class="row26">
<td class="col0"> 2010/05/02 </td><td class="col1"> <a href="http://www.ghostchess.de/" class="urlextern" title="http://www.ghostchess.de/" rel="nofollow"> Ghost</a> </td><td class="col2 centeralign">  2  </td><td class="col3"> Philipp Claßen (Филипп Классен) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Linux32/64; An slightly outdated Windows binary of Ghost 2 (32-bit) </td>
</tr>
<tr class="row27">
<td class="col0"> 2010/05/02 </td><td class="col1"> <a href="http://www.loopchess.com//" class="urlextern" title="http://www.loopchess.com//" rel="nofollow"> Loop 2007</a> </td><td class="col2 centeralign">  2007  </td><td class="col3"> Fritz Reul (Фритц Ройль) </td><td class="col4 centeralign">  <a href="http://www.loopchess.com/loop2007.rar" class="urlextern" title="http://www.loopchess.com/loop2007.rar" rel="nofollow"> Скачать Loop 2007</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Win32+64; стал бесплатным; переименованная версия 13.6 </td>
</tr>
<tr class="row28">
<td class="col0"> 2010/04/29 </td><td class="col1 leftalign"> ChessMind  </td><td class="col2 centeralign">  0.80  </td><td class="col3"> Luca Hemmerich (Лука Хеммерих) </td><td class="col4 centeralign">  <a href="http://www.mediafire.com/?imxzjkrwtkm" class="urlextern" title="http://www.mediafire.com/?imxzjkrwtkm" rel="nofollow"> MediaFire</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> по утверждениям автора играет в силу ~1800 ЭЛО </td>
</tr>
<tr class="row29">
<td class="col0"> 2010/04/24 </td><td class="col1"> Ares </td><td class="col2 centeralign">  1.004  </td><td class="col3"> Charles Roberson (Чарльз Робертсон) </td><td class="col4 centeralign">  <a href="http://wbec-ridderkerk.nl/html/details1/Ares.html" class="urlextern" title="http://wbec-ridderkerk.nl/html/details1/Ares.html" rel="nofollow"> Leo Dijksman</a> <a href="http://www.thorstenczub.de/ares.html" class="urlextern" title="http://www.thorstenczub.de/ares.html" rel="nofollow"> Thorsten Czub</a>  </td><td class="col5 centeralign">  WB, UCI  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row30">
<td class="col0"> 2010/04/21 </td><td class="col1"> <a href="http://www.kimiensoftware.com/littlethought/littlethought.php" class="urlextern" title="http://www.kimiensoftware.com/littlethought/littlethought.php" rel="nofollow"> LittleThought</a> </td><td class="col2 centeralign">  1.051  </td><td class="col3"> Nathan Thom (Натан Том) </td><td class="col4 centeralign">  с оффсайта  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Win32/64; mp; FRC </td>
</tr>
<tr class="row31">
<td class="col0"> 2010/04/21 </td><td class="col1"> Mainsworthy </td><td class="col2 centeralign">  162f  </td><td class="col3"> Mark Ainsworth (Марк Эйнсворт) </td><td class="col4 centeralign">  <a href="http://wbec-ridderkerk.nl/html/details1/Mainsworthy.html" class="urlextern" title="http://wbec-ridderkerk.nl/html/details1/Mainsworthy.html" rel="nofollow"> Leo Dijksman</a> <a href="http://members.lycos.co.uk/mainsworthy/" class="urlextern" title="http://members.lycos.co.uk/mainsworthy/" rel="nofollow"> Lycos</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C++; Win32; собственная <acronym title="Graphical User Interface">GUI</acronym> (другие движки подключить к ней невозможно); T (турнирная) версия - только для длинных контролей времени </td>
</tr>
<tr class="row32">
<td class="col0"> 2010/04/18 </td><td class="col1"> <a href="http://cosinekitty.com/chenard/" class="urlextern" title="http://cosinekitty.com/chenard/" rel="nofollow"> Chenard</a> </td><td class="col2 centeralign">  2010.04.18  </td><td class="col3"> Don Cross (Дон Кросс) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Открытые исходники на C++; использует некторые egtbs; Win32/64, Linux; собственная <acronym title="Graphical User Interface">GUI</acronym> </td>
</tr>
<tr class="row33">
<td class="col0"> 2010/04/17 </td><td class="col1"> <a href="http://agendacom.nuxit.net/index.html" class="urlextern" title="http://agendacom.nuxit.net/index.html" rel="nofollow"> AviChess</a> </td><td class="col2 centeralign">  0.9a  </td><td class="col3"> Michel Gaillard (Мишель Желар) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C source; Win32 </td>
</tr>
<tr class="row34">
<td class="col0"> 2010/04/13 </td><td class="col1"> Arabian Knight </td><td class="col2 centeralign">  1.0.9 JA  </td><td class="col3"> Marcin Gardyjan (Марцин Гардиян) </td><td class="col4 centeralign">  <a href="http://wbec-ridderkerk.nl/html/details1/ArabianKnight.html" class="urlextern" title="http://wbec-ridderkerk.nl/html/details1/ArabianKnight.html" rel="nofollow"> Leo Dijksman</a> <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a> <a href="http://lpps.maciej.szmit.info/programy.html" class="urlextern" title="http://lpps.maciej.szmit.info/programy.html" rel="nofollow"> Polish Engine List</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на Java; своя <acronym title="Graphical User Interface">GUI</acronym>; Win32 </td>
</tr>
<tr class="row35">
<td class="col0"> 2010/04/13 </td><td class="col1"> <a href="http://dshawul.googlepages.com/home" class="urlextern" title="http://dshawul.googlepages.com/home" rel="nofollow"> Scorpio</a> </td><td class="col2 centeralign">  2.5 cluster beta  </td><td class="col3"> Daniel Shawul (Дэниэл Шоул) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a> <a href="http://wbec-ridderkerk.nl/html/details1/Scorpio.html" class="urlextern" title="http://wbec-ridderkerk.nl/html/details1/Scorpio.html" rel="nofollow"> Leo Dijksman</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C++; Win32/64 и Linux 32/64; mp; битбазы в собственном формате </td>
</tr>
<tr class="row36">
<td class="col0"> 2010/04/12 </td><td class="col1"> <a href="http://sites.google.com/site/clonfsp/rodin-chess-engine" class="urlextern" title="http://sites.google.com/site/clonfsp/rodin-chess-engine" rel="nofollow"> Rodin</a> </td><td class="col2 centeralign">  3.0  </td><td class="col3"> Fermin Serrano (Фермин Серрано) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row37">
<td class="col0"> 2010/04/12 </td><td class="col1"> <a href="http://www.stockfishchess.com/" class="urlextern" title="http://www.stockfishchess.com/" rel="nofollow"> Stockfish</a> </td><td class="col2 centeralign">  1.71 JA  </td><td class="col3"> Tord Romstad, Marco Costalba, &amp; Joona Kiiski (Торд Ромстад, Марко Костальба и Йоона Кииски) </td><td class="col4 rightalign">  <a href="http://stockfishchess.com" class="urlextern" title="http://stockfishchess.com" rel="nofollow"> StockfishChess</a> </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на C++; mp; FRC; Win32/64, Linux32/64, Mac; </td>
</tr>
<tr class="row38">
<td class="col0"> 2009/04/10 </td><td class="col1"> <a href="http://www.lehmimkeller.de/chess/n2_index.html" class="urlextern" title="http://www.lehmimkeller.de/chess/n2_index.html" rel="nofollow"> N2</a> </td><td class="col2 centeralign">  0.4  </td><td class="col3"> Ralf Schäfer-Laufen (Ральф Шефер-Лауфен) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Win32/64; Linux32/64 </td>
</tr>
<tr class="row39">
<td class="col0"> 2010/04/10 </td><td class="col1"> <a href="http://evgeniy-korniloff.narod.ru/download.html" class="urlextern" title="http://evgeniy-korniloff.narod.ru/download.html" rel="nofollow"> Woodpecker</a> </td><td class="col2 centeralign">  2.11.5  </td><td class="col3"> Евгений Корнилов </td><td class="col4 centeralign">  <a href="http://www.sbor.net/~e_k/" class="urlextern" title="http://www.sbor.net/~e_k/" rel="nofollow"> Старый сайт</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row40">
<td class="col0"> 2010/04/08 </td><td class="col1"> AliChess </td><td class="col2 centeralign">  4.21  </td><td class="col3"> Anton Lindenmair (Антон Линденмаер) </td><td class="col4 centeralign">  <a href="http://wbec-ridderkerk.nl/html/details1/AliChess.html" class="urlextern" title="http://wbec-ridderkerk.nl/html/details1/AliChess.html" rel="nofollow"> Leo Dijksman</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row41">
<td class="col0"> 2010/04/05 </td><td class="col1"> <a href="http://darczech.ovh.org/lpps/" class="urlextern" title="http://darczech.ovh.org/lpps/" rel="nofollow"> Darmenios</a> </td><td class="col2 centeralign">  0.3  </td><td class="col3"> Dariusz Czechowski (Дариуш Чеховски) </td><td class="col4 centeralign">  <a href="http://darczech.ovh.org/lpps/Darmenios%200.3.32.zip" class="urlextern" title="http://darczech.ovh.org/lpps/Darmenios%200.3.32.zip" rel="nofollow"> 32 bit</a> <a href="http://darczech.ovh.org/lpps/Darmenios%200.3.64.zip" class="urlextern" title="http://darczech.ovh.org/lpps/Darmenios%200.3.64.zip" rel="nofollow"> 64 bit</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32/64 </td>
</tr>
<tr class="row42">
<td class="col0"> 2010/04/05 </td><td class="col1"> <a href="http://translate.google.com/translate?js=y&amp;prev=_t&amp;hl=en&amp;ie=UTF-8&amp;u=http%3A%2F%2Fwww.escacsrubi.com%2Fsimplex%2Fsimplex.html&amp;sl=es&amp;tl=en&amp;history_state0=" class="urlextern" title="http://translate.google.com/translate?js=y&amp;prev=_t&amp;hl=en&amp;ie=UTF-8&amp;u=http%3A%2F%2Fwww.escacsrubi.com%2Fsimplex%2Fsimplex.html&amp;sl=es&amp;tl=en&amp;history_state0=" rel="nofollow"> Simplex</a> </td><td class="col2 centeralign">  0.9.3  </td><td class="col3"> Antonio Torrecillas (Антонио Торресильяс) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на C++ с комментариями на испанском языке; Win32 </td>
</tr>
<tr class="row43">
<td class="col0"> 2010/04/05 </td><td class="col1"> <a href="http://slibo.sourceforge.net/" class="urlextern" title="http://slibo.sourceforge.net/" rel="nofollow"> Slibo</a> </td><td class="col2 centeralign">  Slibo 0.5.1 JA  </td><td class="col3"> Gunther Piez (Гюнтер Пьец) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C; на домашней странице есть Linux <acronym title="Graphical User Interface">GUI</acronym> + движок; JA скомпилировал только WB-движок </td>
</tr>
<tr class="row44">
<td class="col0"> 2010/04/03 </td><td class="col1"> <a href="http://github.com/AaronBecker/daydreamer/tree/master" class="urlextern" title="http://github.com/AaronBecker/daydreamer/tree/master" rel="nofollow"> Daydreamer</a> </td><td class="col2 centeralign">  1.75 JA  </td><td class="col3"> Aaron Becker (Аарон Бекер) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a> <a href="http://cap.connx.com/chess-engines/new-approach/AaronBecker-daydreamer-dda5009.7z" class="urlextern" title="http://cap.connx.com/chess-engines/new-approach/AaronBecker-daydreamer-dda5009.7z" rel="nofollow"> Dann Corbit</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на C; Win32/64, Linux32/64, Mac 32/64; компиляция от DC устарела </td>
</tr>
<tr class="row45">
<td class="col0"> 2010/03/28 </td><td class="col1"> <a href="http://www.marittima.pl/glass" class="urlextern" title="http://www.marittima.pl/glass" rel="nofollow"> Glass</a> </td><td class="col2 centeralign">  1.5  </td><td class="col3"> Edmund Moshammer &amp; Pawel Koziol (Эдмунд Мосхаммер и Павел Козиол) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> дебютная книга в формате *.gob; multiPV </td>
</tr>
<tr class="row46">
<td class="col0"> 2010/03/28 </td><td class="col1"> <a href="http://bloodhound66-numpty.110mb.com/" class="urlextern" title="http://bloodhound66-numpty.110mb.com/" rel="nofollow"> Numpty</a> </td><td class="col2 centeralign">  0.6pr  </td><td class="col3"> Chris Tatham (Крис Тэтам) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на FreeBasic; Win32 </td>
</tr>
<tr class="row47">
<td class="col0"> 2010/03/26 </td><td class="col1"> Booot </td><td class="col2 centeralign">  4.15.1  </td><td class="col3"> Алекс Морозов </td><td class="col4 centeralign">  <a href="http://www.sdchess.ru/download_engines.htm" class="urlextern" title="http://www.sdchess.ru/download_engines.htm" rel="nofollow"> SDChess</a> <a href="http://wbec-ridderkerk.nl/html/details1/Booot.html" class="urlextern" title="http://wbec-ridderkerk.nl/html/details1/Booot.html" rel="nofollow"> Leo Dijksman</a>  </td><td class="col5"> WB, UCI </td><td class="col6"> Исходники на Pascal (комментарии на <em>русском языке</em>); Win32 </td>
</tr>
<tr class="row48">
<td class="col0"> 2010/03/22 </td><td class="col1"> <a href="http://naumchess.brinkster.net/" class="urlextern" title="http://naumchess.brinkster.net/" rel="nofollow"> Naum</a> </td><td class="col2 centeralign">  4.2  </td><td class="col3"> Aleksandar Naumov (Александар Наумов) </td><td class="col4 centeralign">  <a href="http://naumchess.brinkster.net/" class="urlextern" title="http://naumchess.brinkster.net/" rel="nofollow"> Naum</a>  </td><td class="col5 centeralign">  WB, UCI  </td><td class="col6"> Коммерческий; mp; FRC; Win32/64 </td>
</tr>
<tr class="row49">
<td class="col0"> 2010/03/20 </td><td class="col1"> <a href="http://sourceforge.net/projects/protector/" class="urlextern" title="http://sourceforge.net/projects/protector/" rel="nofollow"> Protector</a> </td><td class="col2 centeralign">  1.3.4 JA  </td><td class="col3"> Raimund Heid (Раймунд Хайд) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a> <a href="http://protector.svn.sourceforge.net/viewvc/protector/bin/" class="urlextern" title="http://protector.svn.sourceforge.net/viewvc/protector/bin/" rel="nofollow"> latest builds</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на C; Win32/64, Linux32/64 </td>
</tr>
<tr class="row50">
<td class="col0"> 2010/03/19 </td><td class="col1"> Philou </td><td class="col2 centeralign">  3.1.4.1  </td><td class="col3"> Philippe Gailhac (Филипп Жильяк) </td><td class="col4 centeralign">  <a href="http://wbec-ridderkerk.nl/html/details1/Philou.html" class="urlextern" title="http://wbec-ridderkerk.nl/html/details1/Philou.html" rel="nofollow"> Leo Dijksman</a> <a href="http://sites.google.com/site/strategictestsuite/new-engine-updates/" class="urlextern" title="http://sites.google.com/site/strategictestsuite/new-engine-updates/" rel="nofollow"> Swaminathan</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row51">
<td class="col0"> 2010/03/16 </td><td class="col1"> <a href="http://www.mathieupage.com/s/index.html?p=matmoi.html" class="urlextern" title="http://www.mathieupage.com/s/index.html?p=matmoi.html" rel="nofollow"> MatMoi</a> </td><td class="col2 centeralign">  7.15.0-cct  </td><td class="col3"> Mathieu Pagé (Матьё Паже) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32/64, Linux32/64 </td>
</tr>
<tr class="row52">
<td class="col0"> 2010/03/15 </td><td class="col1"> <a href="http://www.dirtychess.com/" class="urlextern" title="http://www.dirtychess.com/" rel="nofollow"> Dirty</a> </td><td class="col2 centeralign">  14M-22  </td><td class="col3"> Pradu Kannan, Andres Valverde &amp; Fonzy Bluemers (Праду Каннан, Андрес Вальверде и Фонци Блюмерс) </td><td class="col4 centeralign">  <a href="http://webs.ono.com/a.valverde/dirty.htm" class="urlextern" title="http://webs.ono.com/a.valverde/dirty.htm" rel="nofollow"> Старый сайт (медленный)</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row53">
<td class="col0"> 2010/03/15 </td><td class="col1"> <a href="http://pawny.netii.net/" class="urlextern" title="http://pawny.netii.net/" rel="nofollow"> Pawny</a> </td><td class="col2 centeralign">  0.18  </td><td class="col3"> Mincho Georgiev (Минчо Георгиев) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на C; Win32/64, Linux32 </td>
</tr>
<tr class="row54">
<td class="col0"> 2010/03/14 </td><td class="col1"> <a href="http://code.google.com/p/blitzkibitz/" class="urlextern" title="http://code.google.com/p/blitzkibitz/" rel="nofollow"> BlitzKibitz</a> </td><td class="col2 centeralign">  r18 source only  </td><td class="col3"> Valentin Stanciu (Валентин Станчу) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C++; Win32; последний билд r5 </td>
</tr>
<tr class="row55">
<td class="col0"> 2010/03/10 </td><td class="col1"> <a href="http://translate.google.com/translate?u=http%3A%2F%2Fdelphil.neuf.fr&amp;hl=en&amp;ie=UTF-8&amp;sl=fr&amp;tl=en" class="urlextern" title="http://translate.google.com/translate?u=http%3A%2F%2Fdelphil.neuf.fr&amp;hl=en&amp;ie=UTF-8&amp;sl=fr&amp;tl=en" rel="nofollow"> Delphil</a> </td><td class="col2 centeralign">  2.6a  </td><td class="col3"> Philippe Fabiani (Филипп Фабиани) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row56">
<td class="col0"> 2010/03/09 </td><td class="col1"> <a href="http://mnc.chez-alice.fr/SISSA/en/index_en.html" class="urlextern" title="http://mnc.chez-alice.fr/SISSA/en/index_en.html" rel="nofollow"> Sissa</a> </td><td class="col2 centeralign">  1.0 JA  </td><td class="col3"> Christophe J. Mandin (Кристоф Манден) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на C (комментарий в основном на французском и немного на английском); Win32, Linux32 </td>
</tr>
<tr class="row57">
<td class="col0"> 2010/03/09 </td><td class="col1"> Toga II </td><td class="col2 centeralign">  3.1.2SE JA  </td><td class="col3"> Fabian Letouzey, Thomas Gaksch (Фабьен Летузи, Томас Гакш) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на C++; Win32, Linux32 </td>
</tr>
<tr class="row58">
<td class="col0"> 2010/03/08 </td><td class="col1"> <a href="http://tweety.pulc.it/pages/pulchess.html" class="urlextern" title="http://tweety.pulc.it/pages/pulchess.html" rel="nofollow"> Pulchess</a> </td><td class="col2 centeralign">  0.3 исходники  </td><td class="col3"> Moreno Carullo (Морено Карулло) </td><td class="col4 centeralign">  <a href="http://github.com/morenocarullo/pulchess" class="urlextern" title="http://github.com/morenocarullo/pulchess" rel="nofollow"> source</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C++ с комментариями на итальяском; Win32, Linux, Mac; последний билд 0.2i </td>
</tr>
<tr class="row59">
<td class="col0"> 2010/03/05 </td><td class="col1"> <a href="http://www.mrlissandrello.com/index.php?option=com_filecabinet&amp;view=files&amp;id=6" class="urlextern" title="http://www.mrlissandrello.com/index.php?option=com_filecabinet&amp;view=files&amp;id=6" rel="nofollow"> Neurone</a> </td><td class="col2 centeralign">  I  </td><td class="col3"> Luca Lissandrello (Лука Лисандрелло) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32; требует .NET Framework 3.5 и выше </td>
</tr>
<tr class="row60">
<td class="col0"> 2010/03/05 </td><td class="col1"> <a href="http://ippolit.wikispaces.com/" class="urlextern" title="http://ippolit.wikispaces.com/" rel="nofollow"> Ippolit</a> </td><td class="col2 centeralign">  разные  </td><td class="col3"> неизвестно </td><td class="col4 centeralign">  <a href="http://www.cyclonechess.com/robbolito.htm" class="urlextern" title="http://www.cyclonechess.com/robbolito.htm" rel="nofollow"> RobboLito 0.09</a> <a href="http://www.cyclonechess.com/Fire.htm" class="urlextern" title="http://www.cyclonechess.com/Fire.htm" rel="nofollow"> Fire 1.2</a> <a href="http://rapidshare.de/files/48988375/Igorrit_0086v9_w32.exe.html" class="urlextern" title="http://rapidshare.de/files/48988375/Igorrit_0086v9_w32.exe.html" rel="nofollow"> Iggorit w32</a> <a href="http://rapidshare.de/files/48988376/Igorrit_0086v9_x64.exe.html" class="urlextern" title="http://rapidshare.de/files/48988376/Igorrit_0086v9_x64.exe.html" rel="nofollow"> Iggorit w64</a> <a href="http://ippolit.wikispaces.com/file/detail/IvanHoe-Beta-999966-Beta.tar" class="urlextern" title="http://ippolit.wikispaces.com/file/detail/IvanHoe-Beta-999966-Beta.tar" rel="nofollow"> IvanHoe v66</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на C; Win32/64 Linux 32; mp; бездоказательно обвиняется в том, что клон Rybk'и; существует множество деривативов, таких как: RobboLito, Igorrit, IvanHoe, Fire; последняя версия: Fire 1.2 </td>
</tr>
<tr class="row61">
<td class="col0"> 2010/03/04 </td><td class="col1"> <a href="ftp://ftp.cis.uab.edu/pub/hyatt/source/" class="urlextern" title="ftp://ftp.cis.uab.edu/pub/hyatt/source/" rel="nofollow"> Crafty</a> </td><td class="col2 centeralign">  23.3  </td><td class="col3"> Bob Hyatt (Боб Хьятт) </td><td class="col4 centeralign">  <a href="http://www.webkikr.com/" class="urlextern" title="http://www.webkikr.com/" rel="nofollow"> Peter Skinner</a> <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett (23.2)</a>  <a href="http://www.computerchess.info/tdbb/phpBB3/viewtopic.php?f=9&amp;t=273" class="urlextern" title="http://www.computerchess.info/tdbb/phpBB3/viewtopic.php?f=9&amp;t=273" rel="nofollow"> Denis P Mendoza</a> <a href="http://cap.connx.com/chess-engines/new-approach/crafty-23.0.exe.bz2" class="urlextern" title="http://cap.connx.com/chess-engines/new-approach/crafty-23.0.exe.bz2" rel="nofollow"> Dann Corbit 64-bit</a> <a href="http://www.top-5000.nl/wbuci.htm" class="urlextern" title="http://www.top-5000.nl/wbuci.htm" rel="nofollow"> Ed Schröder</a> <a href="http://www.chesspraga.cz/download/winboard/craftycito.rar" class="urlextern" title="http://www.chesspraga.cz/download/winboard/craftycito.rar" rel="nofollow"> Crafty Cito</a>  <a href="http://www.chessbase.com/download/engines/crafty/crafty2301.zip" class="urlextern" title="http://www.chessbase.com/download/engines/crafty/crafty2301.zip" rel="nofollow"> Chessbase32</a> <a href="http://www.chessbase.com/download/engines/crafty/crafty2301_x64.zip" class="urlextern" title="http://www.chessbase.com/download/engines/crafty/crafty2301_x64.zip" rel="nofollow"> Chessbase64</a>  </td><td class="col5 centeralign">  WB,CB  </td><td class="col6"> Исходники на C++; mp; Win32/64, Linux </td>
</tr>
<tr class="row62">
<td class="col0"> 2010/03/03 </td><td class="col1"> GChessIV </td><td class="col2 centeralign">  0.2.0  </td><td class="col3"> Andrea Griffini (Андреа Гриффини) </td><td class="col4 centeralign">  <a href="http://e4e6.altervista.org/download.php" class="urlextern" title="http://e4e6.altervista.org/download.php" rel="nofollow"> G6</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row63">
<td class="col0"> 2010/02/25 </td><td class="col1"> <a href="http://sites.google.com/site/beacheschess/" class="urlextern" title="http://sites.google.com/site/beacheschess/" rel="nofollow"> Beaches</a> </td><td class="col2 centeralign">  2.32  </td><td class="col3"> Robert Pope (Роберт Поуп) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row64">
<td class="col0"> 2010/02/24 </td><td class="col1"> RattateChess </td><td class="col2 centeralign">  1.0  </td><td class="col3"> Maurizio Monge (Маурицио Монге) </td><td class="col4 centeralign">  <a href="http://wbec-ridderkerk.nl/html/details1/Rattate.html" class="urlextern" title="http://wbec-ridderkerk.nl/html/details1/Rattate.html" rel="nofollow"> Leo Dijksman</a> <a href="http://cap.connx.com/chess-engines/new-approach/rattatechess.exe.bz2" class="urlextern" title="http://cap.connx.com/chess-engines/new-approach/rattatechess.exe.bz2" rel="nofollow"> Dann Corbit</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C++; Win32, Linux </td>
</tr>
<tr class="row65">
<td class="col0"> 2010/02/22 </td><td class="col1"> <a href="http://computer-chess.org/doku.php?id=computer_chess:engines:myrddin:index" class="urlextern" title="http://computer-chess.org/doku.php?id=computer_chess:engines:myrddin:index" rel="nofollow"> Myrddin</a> </td><td class="col2 centeralign">  0.83  </td><td class="col3"> John Merlino (Джон Мерлино) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row66">
<td class="col0"> 2010/02/21 </td><td class="col1"> <a href="http://jabbachess.blogspot.com/" class="urlextern" title="http://jabbachess.blogspot.com/" rel="nofollow"> Jabba</a> </td><td class="col2 centeralign">  1.0 (Linux)  </td><td class="col3"> Richard Allbert (Ричард Оллберт) </td><td class="col4 centeralign">  <a href="http://cap.connx.com/chess-engines/new-approach/jabba64.exe.bz2" class="urlextern" title="http://cap.connx.com/chess-engines/new-approach/jabba64.exe.bz2" rel="nofollow"> Dann Corbit(Win64)</a>  </td><td class="col5 centeralign">  WB, UCI  </td><td class="col6"> Исходники на C++; Win32/64, Linux, Mac </td>
</tr>
<tr class="row67">
<td class="col0"> 2010/02/16 </td><td class="col1"> <a href="http://lesgames.altervista.org/" class="urlextern" title="http://lesgames.altervista.org/" rel="nofollow"> ECE</a> </td><td class="col2 centeralign">  1.1  </td><td class="col3"> Luigio Viscione (Луиджио Вишионе) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> ECE = Easy Chess Engine; Win32 </td>
</tr>
<tr class="row68">
<td class="col0"> 2010/02/15 </td><td class="col1"> <a href="http://www.arasanchess.org/" class="urlextern" title="http://www.arasanchess.org/" rel="nofollow"> Arasan</a> </td><td class="col2 centeralign">  11.7a  </td><td class="col3"> Jon Dart (Джон Дарт) </td><td class="col4 centeralign">  -  </td><td class="col5"> WB, UCI </td><td class="col6"> Исходники на C++; mp; Win32/64, Linux </td>
</tr>
<tr class="row69">
<td class="col0"> 2010/02/15 </td><td class="col1"> <a href="http://www.alonsoruibal.com/dev/chess/" class="urlextern" title="http://www.alonsoruibal.com/dev/chess/" rel="nofollow"> Carballo</a> </td><td class="col2 centeralign">  0.4 JA  </td><td class="col3"> Alberto Alonso Ruibal (Альберто Руйбал) </td><td class="col4 centeralign">  <a href="http://sourceforge.net/projects/carballo/" class="urlextern" title="http://sourceforge.net/projects/carballo/" rel="nofollow"> sourceforge</a> <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на Java; апплет для игры онлайн </td>
</tr>
<tr class="row70">
<td class="col0"> 2010/02/13 </td><td class="col1"> <a href="http://home.comcast.net/~blais_normand/" class="urlextern" title="http://home.comcast.net/~blais_normand/" rel="nofollow"> Alex</a> </td><td class="col2 centeralign">  2.03  </td><td class="col3"> Normand Marcel Blais (Норман Марсель Блез) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB, UCI  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row71">
<td class="col0"> 2010/02/13 </td><td class="col1"> <a href="http://sites.google.com/site/sungorus/" class="urlextern" title="http://sites.google.com/site/sungorus/" rel="nofollow"> Sungorus</a> </td><td class="col2 centeralign">  1.3 JA  </td><td class="col3"> Pablo Vazquez (Пабло Васкес) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на C; Win32/64, Linux 32/64 </td>
</tr>
<tr class="row72">
<td class="col0"> 2010/02/11 </td><td class="col1"> Counter </td><td class="col2 centeralign">  1.2  </td><td class="col3"> Вадим Чижов </td><td class="col4 centeralign">  <a href="http://www.sdchess.ru/download_engines.htm" class="urlextern" title="http://www.sdchess.ru/download_engines.htm" rel="nofollow"> SDChess</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row73">
<td class="col0"> 2010/02/11 </td><td class="col1"> <a href="http://john.stanback.net/" class="urlextern" title="http://john.stanback.net/" rel="nofollow"> SCP/GnuChess</a> </td><td class="col2 centeralign">  2.03 JA  </td><td class="col3"> John Stanback (Джон Стэнбэк) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> JA сделал WB-билд; Win32/64, Linux32/64; SCP == Stanback Chess Program aka GnuChess; Это последняя версия GnuChess с участием Джона Стэнбэка </td>
</tr>
<tr class="row74">
<td class="col0"> 2010/02/11 </td><td class="col1"> ZZZZZZ </td><td class="col2 centeralign">  3.5.1 JA  </td><td class="col3"> Gijsbert Wiesenekker  &amp; Jim Ablett (Гийсберт Визенеккер и Джим Аблетт) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C; исправлено JA; Win32, Linux32 </td>
</tr>
<tr class="row75">
<td class="col0"> 2010/02/10 </td><td class="col1"> <a href="http://www.chessbase.com/shop/product.asp?pid=488" class="urlextern" title="http://www.chessbase.com/shop/product.asp?pid=488" rel="nofollow"> Fritz (Deep Fritz)</a> </td><td class="col2 centeralign">  12  </td><td class="col3"> Franz Morsch (Франц Морш) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  CB  </td><td class="col6"> коммерческий; mp; Win32 </td>
</tr>
<tr class="row76">
<td class="col0"> 2010/02/07 </td><td class="col1"> <a href="http://www.stefanomalloggi.altervista.org/index.htm" class="urlextern" title="http://www.stefanomalloggi.altervista.org/index.htm" rel="nofollow"> Chaturanga</a> </td><td class="col2 centeralign">  2.4.3  </td><td class="col3"> Stefano Malloggi (Стефано Маллоджи) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32; Не имеет отношения к Chaturanga (1981-1982) </td>
</tr>
<tr class="row77">
<td class="col0"> 2010/02/07 </td><td class="col1"> <a href="http://jdtaylor.org/" class="urlextern" title="http://jdtaylor.org/" rel="nofollow"> Dendron</a> </td><td class="col2 centeralign">  0.42b JA  </td><td class="col3"> James D Taylor (Джеймс Тейлор) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C++; </td>
</tr>
<tr class="row78">
<td class="col0"> 2010/02/04 </td><td class="col1"> <a href="http://sourceforge.net/projects/redqueenchess/" class="urlextern" title="http://sourceforge.net/projects/redqueenchess/" rel="nofollow"> Redqueen</a> </td><td class="col2 centeralign">  0.4 JA  </td><td class="col3"> Ben-Hur Carlos Langoni Júnior (Бен-Гур Карлос Лангони) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на C++; Win32/64, Linux32/64 </td>
</tr>
<tr class="row79">
<td class="col0"> 2010/02/03 </td><td class="col1"> <a href="http://ed.apostol.googlepages.com/home" class="urlextern" title="http://ed.apostol.googlepages.com/home" rel="nofollow"> Twisted Logic</a> </td><td class="col2 centeralign">  20100131  </td><td class="col3"> Edsel Apostol (Эдсель Апостол) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB, UCI  </td><td class="col6"> Win32/64 </td>
</tr>
<tr class="row80">
<td class="col0"> 2010/02/01 </td><td class="col1"> <a href="http://code.google.com/p/magnumchess/" class="urlextern" title="http://code.google.com/p/magnumchess/" rel="nofollow"> MagnumChess</a> </td><td class="col2 centeralign">  2.00 JA  </td><td class="col3"> Eric Stock (Эрик Сток) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на Java; Win32 </td>
</tr>
<tr class="row81">
<td class="col0"> 2010/01/28 </td><td class="col1"> <a href="http://scid.sourceforge.net/scidlet.html" class="urlextern" title="http://scid.sourceforge.net/scidlet.html" rel="nofollow"> Scidlet</a> </td><td class="col2 centeralign">  3.61 b2 JA  </td><td class="col3"> Shane Hudson (Шейн Хадсон) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C++; Win32/64, Linux32/64; входит в оболочку SCID </td>
</tr>
<tr class="row82">
<td class="col0"> 2010/01/27 </td><td class="col1"> <a href="http://www.xs4all.nl/~vermeire/brutus.html" class="urlextern" title="http://www.xs4all.nl/~vermeire/brutus.html" rel="nofollow"> Brutus</a> </td><td class="col2 centeralign">  8.05 JA  </td><td class="col3"> Stephan Vermeire &amp; Maurizio Platino (Стефан Вермер и Маурицио Платино) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB, UCI  </td><td class="col6"> Исходники на C++ (MSVC), Win32/64, mp </td>
</tr>
<tr class="row83">
<td class="col0"> 2010/01/26 </td><td class="col1"> <a href="http://web.telia.com/~u89404340/javachess/index.html" class="urlextern" title="http://web.telia.com/~u89404340/javachess/index.html" rel="nofollow"> CuckooChess</a> </td><td class="col2 centeralign">  1.04  </td><td class="col3"> Peter Osterlund (Петер Остерлунд) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Исходники на Java; своя <acronym title="Graphical User Interface">GUI</acronym>; использует <a href="http://en.wikipedia.org/wiki/Cuckoo_hashing" class="urlextern" title="http://en.wikipedia.org/wiki/Cuckoo_hashing" rel="nofollow"> Хэширование Cuckoo</a> </td>
</tr>
<tr class="row84">
<td class="col0"> 2010/01/26 </td><td class="col1"> <a href="http://home.arcor.de/dreamlike/chess/index.html" class="urlextern" title="http://home.arcor.de/dreamlike/chess/index.html" rel="nofollow"> OliThink</a> </td><td class="col2 centeralign">  5.3.0 JA  </td><td class="col3"> Oliver Brausch (Оливер Брауш) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett</a> <a href="http://rapidshare.de/files/48975337/OliThink529_x64.zip.html" class="urlextern" title="http://rapidshare.de/files/48975337/OliThink529_x64.zip.html" rel="nofollow"> Алекс Лобанов (Win64)</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C и Java; своя <acronym title="Graphical User Interface">GUI</acronym> (Java только); Win32/64, Linux32/64 </td>
</tr>
<tr class="row85">
<td class="col0"> 2010/01/18 </td><td class="col1"> <a href="http://protej.info/" class="urlextern" title="http://protej.info/" rel="nofollow"> Protej</a> </td><td class="col2 centeralign">  0.57  </td><td class="col3"> Alex Brunetti (Алекс Брунетти) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB, UCI  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row86">
<td class="col0"> 2010/01/16 </td><td class="col1"> <a href="http://alfilchess.googlepages.com/" class="urlextern" title="http://alfilchess.googlepages.com/" rel="nofollow"> Alfil</a> </td><td class="col2 centeralign">  10.1  </td><td class="col3"> Enrique Sánchez Acosta (Энрике Санчес Акоста) </td><td class="col4 centeralign">  -  </td><td class="col5"> WB, UCI </td><td class="col6"> Win32 (версия 8.1.1); Linux </td>
</tr>
<tr class="row87">
<td class="col0"> 2010/01/14 </td><td class="col1"> <a href="http://nanochess.110mb.com/" class="urlextern" title="http://nanochess.110mb.com/" rel="nofollow"> Toledo Nanochess</a> </td><td class="col2 centeralign">  Jan/14/2010  </td><td class="col3"> Oscar Toledo (Оскар Толедо) </td><td class="col4 centeralign">  <a href="http://www.mediafire.com/?ojn4ejmhx0z" class="urlextern" title="http://www.mediafire.com/?ojn4ejmhx0z" rel="nofollow"> Jim Ablett</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C; самые маленькие исходники для движка </td>
</tr>
<tr class="row88">
<td class="col0"> 2010/01/13 </td><td class="col1"> <a href="http://sourceforge.net/projects/kmtchess/" class="urlextern" title="http://sourceforge.net/projects/kmtchess/" rel="nofollow"> KMT Chess</a> </td><td class="col2 centeralign">  1.2.1  </td><td class="col3"> Paul Villanueva (Пауль Вильянуэва) </td><td class="col4 centeralign">  <a href="http://cap.connx.com/chess-engines/new-approach/kmtchess64.exe.bz2" class="urlextern" title="http://cap.connx.com/chess-engines/new-approach/kmtchess64.exe.bz2" rel="nofollow"> Dann Corbit (x64)</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C++ (на испанском); Win32/64; использует BookThinker </td>
</tr>
<tr class="row89">
<td class="col0"> 2010/01/12 </td><td class="col1"> <a href="http://bomcao.t35.com/damas/damas.htm" class="urlextern" title="http://bomcao.t35.com/damas/damas.htm" rel="nofollow"> Cleo</a> </td><td class="col2 centeralign">  1  </td><td class="col3"> William Mota (Вильям Мота) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32 </td>
</tr>
<tr class="row90">
<td class="col0"> 2010/01/12 </td><td class="col1"> <a href="http://bomcao.t35.com/damas/damas.htm" class="urlextern" title="http://bomcao.t35.com/damas/damas.htm" rel="nofollow"> Damas</a> </td><td class="col2 centeralign">  9  </td><td class="col3"> William Mota (Вильям Мота) </td><td class="col4 centeralign">  <a href="http://cap.connx.com/chess-engines/new-approach/damas.zip" class="urlextern" title="http://cap.connx.com/chess-engines/new-approach/damas.zip" rel="nofollow"> Dann Corbit</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32; DC версия устарела </td>
</tr>
<tr class="row91">
<td class="col0"> 2010/01/12 </td><td class="col1"> Mephisto </td><td class="col2 centeralign">  MM V  </td><td class="col3"> Ed Schröeder (and Richard Lang?)(Эд Шрёдер и Ричард Ланг?) </td><td class="col4 centeralign">  <a href="http://www.top-5000.nl/dl/dedicated.zip" class="urlextern" title="http://www.top-5000.nl/dl/dedicated.zip" rel="nofollow"> прямая ссылка</a> <a href="http://www.lehmimkeller.de/chess_mess/download/winboard/Mess_Mephisto_134a_Winboard.zip" class="urlextern" title="http://www.lehmimkeller.de/chess_mess/download/winboard/Mess_Mephisto_134a_Winboard.zip" rel="nofollow"> альтернативная ссылка</a>  </td><td class="col5 centeralign">  Примечания  </td><td class="col6"> движок можно сделать WB-совместимым при помощи ROM-эмулятора, подробнее <a href="http://www.talkchess.com/forum/viewtopic.php?topic_view=threads&amp;p=318438&amp;t=31660&amp;sid=7e76f457c785353212a79a6e9e545af1" class="urlextern" title="http://www.talkchess.com/forum/viewtopic.php?topic_view=threads&amp;p=318438&amp;t=31660&amp;sid=7e76f457c785353212a79a6e9e545af1" rel="nofollow"> тут</a> и <a href="http://translate.google.com/translate?js=y&amp;prev=_t&amp;hl=en&amp;ie=UTF-8&amp;layout=1&amp;eotf=1&amp;u=http%3A%2F%2Fwww.schachcomputer.info%2Fforum%2Fshowthread.php%3Ft%3D1448%26page%3D35&amp;sl=de&amp;tl=en" class="urlextern" title="http://translate.google.com/translate?js=y&amp;prev=_t&amp;hl=en&amp;ie=UTF-8&amp;layout=1&amp;eotf=1&amp;u=http%3A%2F%2Fwww.schachcomputer.info%2Fforum%2Fshowthread.php%3Ft%3D1448%26page%3D35&amp;sl=de&amp;tl=en" rel="nofollow"> здесь</a> </td>
</tr>
<tr class="row92">
<td class="col0"> 2010/01/12 </td><td class="col1"> <a href="http://www.chessbox.de/Octopus/C.Schach/Eintrage/2009/12/29_10x8-Schachprogramm_SMIRF_in_einem_internationalen_Turnier.html" class="urlextern" title="http://www.chessbox.de/Octopus/C.Schach/Eintrage/2009/12/29_10x8-Schachprogramm_SMIRF_in_einem_internationalen_Turnier.html" rel="nofollow"> Smirf</a> </td><td class="col2 centeralign">  <acronym title="Microsoft">MS</acronym>-176b  </td><td class="col3"> Reinhard Scharnagl (Рейнхард Шарнагль) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  См. примечание  </td><td class="col6"> «donationware» движок, Winboard-совместимый при помощи <a href="http://home.hccnet.nl/h.g.muller/smirf.html" class="urlextern" title="http://home.hccnet.nl/h.g.muller/smirf.html" rel="nofollow"> Smirfoglot адаптера</a>; своя <acronym title="Graphical User Interface">GUI</acronym>, но движок можно скачать отдельно </td>
</tr>
<tr class="row93">
<td class="col0"> 2010/01/11 </td><td class="col1"> <a href="http://evgeniy-korniloff.narod.ru/download.html" class="urlextern" title="http://evgeniy-korniloff.narod.ru/download.html" rel="nofollow"> Chess One</a> </td><td class="col2 centeralign">  3.x, build 5  </td><td class="col3"> Евгений Корнилов </td><td class="col4 centeralign">  <a href="http://www.sbor.net/~e_k/" class="urlextern" title="http://www.sbor.net/~e_k/" rel="nofollow"> ещё сайт</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32; не связан с программой 'Chess'; поэтому переименована </td>
</tr>
<tr class="row94">
<td class="col0"> 2010/01/10 </td><td class="col1"> <a href="http://members.ziggo.nl/allard.siemelink/bright/" class="urlextern" title="http://members.ziggo.nl/allard.siemelink/bright/" rel="nofollow"> Bright</a> </td><td class="col2 centeralign">  0.5c  </td><td class="col3"> Allard Siemelink (Аллард Симмелинк) </td><td class="col4 centeralign">  <a href="http://brightchess.googlepages.com/" class="urlextern" title="http://brightchess.googlepages.com/" rel="nofollow"> Googlepages</a>  </td><td class="col5 centeralign">  UCI  </td><td class="col6"> Win 32; mp, FRC; использует Scorpio egbbs; Исходники на C++ </td>
</tr>
<tr class="row95">
<td class="col0"> 2010/01/08 </td><td class="col1"> <a href="http://www.geocities.com/taciturn_lemon/" class="urlextern" title="http://www.geocities.com/taciturn_lemon/" rel="nofollow"> Lime</a> </td><td class="col2 centeralign">  KM 62.1 JA  </td><td class="col3"> Richard Allbert (Ричард Оллберт) </td><td class="col4 centeralign">  <a href="http://homepages.tesco.net/henry.ablett/jims.html" class="urlextern" title="http://homepages.tesco.net/henry.ablett/jims.html" rel="nofollow"> Jim Ablett (игра в Knightmate и Knightrider только)</a> <a href="http://wbec-ridderkerk.nl/html/details1/Lime.html" class="urlextern" title="http://wbec-ridderkerk.nl/html/details1/Lime.html" rel="nofollow"> Leo Dijksman</a>  </td><td class="col5"> WB, UCI </td><td class="col6"> Исходники на C </td>
</tr>
<tr class="row96">
<td class="col0"> 2010/01/06 </td><td class="col1"> <a href="http://sites.google.com/site/gaviotachessengine/" class="urlextern" title="http://sites.google.com/site/gaviotachessengine/" rel="nofollow"> Gaviota</a> </td><td class="col2 centeralign">  0.74.41  </td><td class="col3"> Miguel A. Ballicora (Мигель Балликора) </td><td class="col4 centeralign">  <a href="http://www.msu.edu/~ballicor/gav/" class="urlextern" title="http://www.msu.edu/~ballicor/gav/" rel="nofollow"> old site</a>  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Win32/64, Linux32/64; собственные эндшпильные базы </td>
</tr>
<tr class="row97">
<td class="col0"> 2010/01/02 </td><td class="col1"> <a href="http://code.google.com/p/gray-matter/" class="urlextern" title="http://code.google.com/p/gray-matter/" rel="nofollow"> Gray Matter</a> </td><td class="col2 centeralign">  rev. 1590  </td><td class="col3"> Rajiv Bakulesh Shah &amp; team (Раджив Бакулеш Шах) </td><td class="col4 centeralign">  -  </td><td class="col5 centeralign">  WB  </td><td class="col6"> Исходники на C++; Win32/64, Linux </td>
</tr>
