alias g='git'
alias ls='ls -GFh'
alias ll='ls -GFhl'
alias ri='ri -Tf ansi'
alias rdoc='rdoc --ri --line-numbers --all'
alias e='emacs -nw'
alias emacs='emacs -nw'
alias cycle_passenger='touch tmp/restart.txt'
